### ISSUE TITLE
Relicense under Apache 2.0 + MIT

### ISSUE THREAD

**Issue by belak** [belak/serde-xmlrpc#12]
It probably makes sense to re-license this to be more in line with usual best practices in the Rust community. I meant to do this earlier, but never got around to it.

Even though it would probably be OK to just change it, because we now have additional contributors, to be safe I'm looking for permission to relicense.

CC @Carter12s @blaenk

**Comment by blaenk** [comment]
You have my permission to relicense under Apache 2.0 + MIT.

**Comment by Carter12s** [comment]
2nd'd full support!

**Comment by belak** [comment]
Thanks for the quick responses! The next release will be licensed under both MIT and Apache-2.0!
