### ISSUE TITLE
Works fine, but dependencies need an upgrade due to breaking language change.

### ISSUE THREAD

**Issue by John-Nagle** [belak/serde-xmlrpc#21]
Depends on quick-xml 0.17.2, which is currently at 0.31.0, and an old version of iso8601, which depends on an old version of nom.

The old versions "contain code that will be rejected by a future version of Rust", so things will break without an upgrade.

**Comment by belak** [comment]
Thanks for reporting this! I believe this was fixed about 10 months ago with the release of 0.2. Please let me know if you're still having problems.

**Comment by John-Nagle** [comment]
It looks like the simple-xmlrpc crate needs to be pushed to crates.io.

**Comment by belak** [comment]
Interesting - I forgot about simple-xmlrpc. I'm showing [serde_xmlrpc](https://crates.io/crates/serde_xmlrpc) at 0.2 already. I'll have to figure out how to deprecate simple-xmlrpc.

**Comment by belak** [comment]
I never intended simple-xmlrpc to be used at all (and it was pushed by accident before I renamed the library), but I've dug up the old code, marked all relevant functions as deprecated and pushed a new version to crates.io.

All users of simple-xmlrpc should migrate to serde-xmlrpc when possible.

**Comment by belak** [comment]
I looked into releasing a new version of simple-xmlrpc backed by serde_xmlrpc, but because the function signature changed from `response -> Value` to `response -> T where T: Deserialize`, there wasn't a clear way to port that function. I don't really have the time or energy to properly do that port, and (almost) nobody should be using it anyway, so I'm going to close this.

Thanks for bringing it up.

**Comment by John-Nagle** [comment]
> All users of simple-xmlrpc should migrate to serde-xmlrpc when possible.

Trying...

response_from_str won't deserialize to Value.

Trait Deserialize is not implemented for serde_xmlrpc::Value.

No obvious equivalent for parse_response(data: &[str](https://doc.rust-lang.org/nightly/std/primitive.str.html)) -> [Result](https://docs.rs/simple-xmlrpc/latest/simple_xmlrpc/type.Result.html)<[Value](https://docs.rs/simple-xmlrpc/latest/simple_xmlrpc/enum.Value.html)>

**Comment by belak** [comment]
Let me take one more look - I could have sworn I properly implemented Deserialize for Value.

**Comment by belak** [comment]
I've pushed v0.2.2 which adds `impl serde::Deserialize for Value` so `response_from_str` should work as expected with the `Value` type. Good catch. Sorry for the confusion.

**Comment by belak** [comment]
When I have time later, I'll try to release simple-xmlrpc v0.1.2 which will back all the functions with simple-xmlrpc v0.2.3 or higher.

**Comment by John-Nagle** [comment]
Thanks. Using serde-xmlrpc now. No need for simple-xmlrpc any more. Application is working. No more scary warnings from rustc that it will stop working due to a deprecated macro format in some old version of nom.
