### ISSUE TITLE
Would pull requests implementing request parsing be accepted and published?

### ISSUE THREAD

**Issue by Carter12s** [belak/serde-xmlrpc#6]
Heyo, I'm working on adding native ROS1 support to [roslibrust](https://github.com/Carter12s/roslibrust). The requires the ability to both make xmlrpc calls and to run an xmlrpc server which responds to requests.

I've had great success using this crate for making requests, but realize it doesn't have functionality for parsing a request as you'd want to on the server side. After looking at the other xmlrpc implementations available for Rust, I think I'd prefer to add that functionality to this crate rather than switch to any of the others.

This repo seems fairly inactive since 2020, and I'd prefer to not publish yet another xmlrpc crate variant, but to expand this one. So my main question is: is maintenance of this crate active enough that If I made some substantial PRs the could be merged and published in relatively short time?

Would offer to join as a maintainer of this repo / crate if that is an option?

**Comment by belak** [comment]
That would be great! I'd be happy to take a look at and merge PRs adding better functionality for server side request parsing. If you're willing to submit one or two small PRs to show you know what you're doing, I'd be happy to add you as a maintainer as well.

**Comment by Carter12s** [comment]
Awesome!

Expect a few coming in over the next few days.

**Comment by belak** [comment]
I'll keep and eye out for them and try to stay on top of reviews. Thanks for reaching out!

**Comment by belak** [comment]
Thanks for your PRs and the review! I've invited you as a collaborator to the repo so you can have write access.

**Comment by Carter12s** [comment]
Awesome, I accepted! Thank you for the trust and hopefully I add some bus factor.

Currently working on trying to figure out an elegant way to de-structure `Vec<Value>` into a tuple of different types. After I get that MR up this is likely feature complete for what I'm looking for with `roslibrust` and I'll ask for you to cut a v0.2.0.
